In [1]:
from tools import show_subtitle
from mxnet import np,npx
npx.set_np()

# Ch02. Preliminaries(预备知识)
## 2.1 Data Manipulation(数据操作)
### 2.1.1 Getting Started

In [2]:
x=np.arange(12)
print("x=",x)
print("x.shape=",x.shape)
print("x.size=",x.size)

X=x.reshape(3,4)
print("X=")
print(X)

x= [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
x.shape= (12,)
x.size= 12
X=
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [3]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [4]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
np.random.normal(0,1,size=(3,4))

array([[ 1.1630785 ,  2.2122061 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.558071  , -1.2347414 ]])

### 2.1.2 Operations

In [6]:
x=np.array([1,2,4,8])
y=np.array([2,2,2,2])
x+y, x-y, x*y, x/y, x**y

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [7]:
x=np.array([1,2,4,8])
np.exp(x)

array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03])

In [8]:
X=np.arange(12).reshape(3,4)
Y=np.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
show_subtitle("X")
print(X)
show_subtitle("Y")
print(Y)
show_subtitle("np.concatenate")
np.concatenate([X,Y],axis=0),np.concatenate([X,Y],axis=1)

--------------- >X< ---------------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
--------------- >Y< ---------------
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
--------------- >np.concatenate< ---------------


(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [9]:
X==Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [10]:
X.sum()

array(66.)

### 2.1.3 Broadcasting Mechanism

In [11]:
a=np.arange(3).reshape(3,1)
b=np.arange(2).reshape(1,2)
a,b,a+b

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1.]]),
 array([[0., 1.],
        [1., 2.],
        [2., 3.]]))

### 2.1.4 Indexing and Slicing

In [12]:
X=np.arange(12).reshape(3,4)
Y=np.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
X, X[-1], X[1:3]

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([ 8.,  9., 10., 11.]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [13]:
X[1,2]=9
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [14]:
X[0:2,:]=12
X

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]])

### 2.1.5 Saving Memory

In [15]:
# id() 是 Python 的地址函数
before=id(Y)
Y=Y+X
before, id(Y)==before

(1996298226624, False)

In [16]:
Z=np.zeros_like(Y)
print("id(Z)=",id(Z))
Z[:]=X+Y
print("id(Z)=",id(Z))

id(Z)= 1996019675712
id(Z)= 1996019675712


In [17]:
before=id(X)
X+=Y
id(X)==before

True

### 2.1.6 Conversion to Other Python Objects

In [18]:
A=X.asnumpy()
B=np.array(A)
C=np.array([1,3,5])
type(A), type(B), type(C)

(numpy.ndarray, mxnet.numpy.ndarray, mxnet.numpy.ndarray)

In [19]:
a=np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)