# 5.6 GPUs

In [1]:
# 5.6.1 Computing Devices
from mxnet import np,npx
from mxnet.gluon import nn
npx.set_np()
npx.cpu(),npx.gpu(),npx.gpu(1),npx.num_gpus()

(cpu(0), gpu(0), gpu(1), 1)

In [3]:
def try_gpu(i=0):
    return npx.gpu(i) if npx.num_gpus()>= i+1 else npx.cpu()
def try_all_gpus():
    devices=[npx.gpu(i) for i in range(npx.num_gpus())]
    return devices if devices else [npx.cpu()]
try_gpu(), try_gpu(10),try_all_gpus()    

(gpu(0), cpu(0), [gpu(0)])

In [4]:
# 5.6.2 Tensors and GPUs
x=np.array([1,2,3])
x.ctx

cpu(0)

In [9]:
# Storage on the GPU
X=np.ones((2,3),ctx=try_gpu())
X

array([[1., 1., 1.],
       [1., 1., 1.]], ctx=gpu(0))

In [10]:
Y=np.random.uniform(size=(2,3),ctx=try_gpu(1))
Y

array([[0.4375872 , 0.2975346 , 0.891773  ],
       [0.05671298, 0.96366274, 0.2726563 ]])

In [11]:
# Copying
Z=X.copyto(try_gpu(1))
X,Z

(array([[1., 1., 1.],
        [1., 1., 1.]], ctx=gpu(0)),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [13]:
# Note：必须在同样的计算设备上才可以进行计算
# X+Y
Y+Z

array([[1.4375873, 1.2975346, 1.891773 ],
       [1.056713 , 1.9636627, 1.2726563]])

In [17]:
Y.as_in_ctx(try_gpu())+X

array([[1.4375873, 1.2975346, 1.891773 ],
       [1.056713 , 1.9636627, 1.2726563]], ctx=gpu(0))

In [18]:
# Side Notes ?

In [19]:
# 5.6.3 Neural Networks and GPUs
net=nn.Sequential()
net.add(nn.Dense(1))
net.initialize(ctx=try_gpu())
net(X)

array([[0.02139644],
       [0.02139644]], ctx=gpu(0))