## 5.5 File I/O
### 5.5.1 Loading and Saving Tensors

In [1]:
from mxnet import np,npx
from mxnet.gluon import nn
npx.set_np()

In [8]:
x=np.arange(4)
npx.save('tmp/x-file',x)
x

array([0., 1., 2., 3.])

In [9]:
x2=npx.load('tmp/x-file')
x2

[array([0., 1., 2., 3.])]

In [10]:
y=np.zeros(4)
npx.save('tmp/x-files',[x,y])
x,y

(array([0., 1., 2., 3.]), array([0., 0., 0., 0.]))

In [11]:
x2,y2=npx.load('tmp/x-files')
x2,y2

(array([0., 1., 2., 3.]), array([0., 0., 0., 0.]))

In [12]:
mydict={'x':x,'y':y}
npx.save('tmp/mydict',mydict)
mydict

{'x': array([0., 1., 2., 3.]), 'y': array([0., 0., 0., 0.])}

In [13]:
mydict2=npx.load('tmp/mydict')
mydict2

{'x': array([0., 1., 2., 3.]), 'y': array([0., 0., 0., 0.])}

In [14]:
# 5.5.2 Loading and Saving Model Parameters
class MLP(nn.Block):
    def __init__(self,**kwargs):
        super(MLP,self).__init__(**kwargs)
        self.hidden=nn.Dense(256,activation='relu')
        self.output=nn.Dense(10)
    def forward(self,x):
        return self.output(self.hidden(x))

net=MLP()
net.initialize()
X=np.random.uniform(size=(2,20))
y=net(X)
net.save_parameters('tmp/mlp.params')

In [15]:
clone=MLP()
clone.load_parameters('tmp/mlp.params')
y_clone=clone(X)
y_clone==y

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])