## 6.5 Pooling

In [1]:
from d2l import mxnet as d2l
from mxnet import np,npx
from mxnet.gluon import nn
npx.set_np()

### 6.5.1 Maximum Pooling and Average Pooling

In [3]:
def pool2d(X,pool_size,mode='max'):
    p_h,p_w=pool_size
    Y=np.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':Y[i,j]=X[i:i+p_h,j:j+p_w].max()
            elif mode=='avg':Y[i,j]=X[i:i+p_h,j:j+p_w].mean()
    return Y

In [4]:
X=np.arange(9).reshape(3,3)
pool2d(X,(2,2))

array([[4., 5.],
       [7., 8.]])

In [5]:
pool2d(X,(2,2),'avg')

array([[2., 3.],
       [5., 6.]])

### 6.5.2 Padding and Stride

In [6]:
X=d2l.reshape(np.arange(16,dtype=np.float32),(1,1,4,4))
pool2d=nn.MaxPool2D(3)
pool2d(X)

array([[[[10.]]]])

In [8]:
pool2d=nn.MaxPool2D(3,padding=1,strides=2)
pool2d(X)

array([[[[ 5.,  7.],
         [13., 15.]]]])

In [11]:
pool2d=nn.MaxPool2D((2,3),padding=(1,2),strides=(2,3))
pool2d(X)

array([[[[ 0.,  3.],
         [ 8., 11.],
         [12., 15.]]]])

### 6.5.3 Multiple Channels

In [16]:
X2=np.concatenate((X,X+1),1)
X3=np.stack((X,X+1),1)
X.shape,X2.shape,X3.shape

((1, 1, 4, 4), (1, 2, 4, 4), (1, 2, 1, 4, 4))

In [19]:
pool2d=nn.MaxPool2D(3,padding=1,strides=2)
pool2d(X),pool2d(X2)

(array([[[[ 5.,  7.],
          [13., 15.]]]]),
 array([[[[ 5.,  7.],
          [13., 15.]],
 
         [[ 6.,  8.],
          [14., 16.]]]]))