## 6.4 Multiple Input and Multiple Output Channels

In [1]:
from d2l import mxnet as d2l
from mxnet import np,npx
npx.set_np()

### 6.4.1 Multiple Input Single Output Channels

In [2]:
def corr2d_multi_in(X,K):
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))

In [6]:
X=np.array([
    [[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]],
    [[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]
    ])
K=np.array([
    [[0.0,1.0],[2.0,3.0]],
    [[1.0,2.0],[3.0,4.0]]
    ])
print(corr2d_multi_in(X,K))

X=np.stack([np.arange(9).reshape(3,3),np.arange(1,10).reshape(3,3)],0)
K=np.stack([np.arange(4).reshape(2,2),np.arange(1,5).reshape(2,2)],0)
print(corr2d_multi_in(X,K))

[[ 56.  72.]
 [104. 120.]]
[[ 56.  72.]
 [104. 120.]]


### 6.4.2 Multiple Input Multiple Output Channels

In [7]:
def corr2d_multi_in_out(X,K):
    return np.stack([corr2d_multi_in(X,k) for k in K],0)

In [13]:
K2=np.stack((K,K+1,K+2),0)
K2.shape

(3, 2, 2, 2)

In [14]:
corr2d_multi_in_out(X,K2)

array([[[ 56.,  72.],
        [104., 120.]],

       [[ 76., 100.],
        [148., 172.]],

       [[ 96., 128.],
        [192., 224.]]])

In [15]:
### 6.4.3 1x1 Convolutional Layer
def corr2d_multi_in_out_1x1(X,K):
    c_i,h,w=X.shape
    c_o=K.shape[0]
    X=X.reshape((c_i,h*w))
    K=K.reshape((c_o,c_i))
    Y=np.dot(K,X)
    return Y.reshape((c_o,h,w))

In [19]:
X=np.random.normal(0,1,(3,3,3))
K=np.random.normal(0,1,(2,3,1,1))
Y1=corr2d_multi_in_out_1x1(X,K)
Y2=corr2d_multi_in_out(X,K)
assert float(d2l.reduce_sum(np.abs(Y1-Y2)))<1e-6
Y1.shape,Y2.shape

((2, 3, 3), (2, 3, 3))