## 2.3 Linear Algebra
### 2.3.1 Scalars(标量)

In [3]:
from mxnet import np,npx
npx.set_np()
x,y =np.array(3.0), np.array(2.0)
x+y, x-y, x*y, x/y, x**y

(array(5.), array(1.), array(6.), array(1.5), array(9.))

### 2.3.2 Vectors(向量)

In [4]:
x=np.arange(4)
x, x[3], len(x), x.shape

(array([0., 1., 2., 3.]), array(3.), 4, (4,))

### 2.3.3 Matrices

In [5]:
A=np.arange(20).reshape(5,4)
A, A.T

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]]))

In [6]:
B=np.array([[1,2,3],[2,0,4],[3,4,5]])
B==B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 2.3.4 Tensors(张量)

In [7]:
X=np.arange(24).reshape(2,3,4)
X, X.T

(array([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],
 
        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]),
 array([[[ 0., 12.],
         [ 4., 16.],
         [ 8., 20.]],
 
        [[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],
 
        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],
 
        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]]]))

### 2.3.5 Basic Properties of Tensor Arithmetic(张量代数)

In [8]:
A=np.arange(20).reshape(5,4)
B=A.copy()  # 分配新的内存，存放 A 的复制值
A, A+B, A*B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]),
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]),
 array([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]]))

In [9]:
a=2
X=np.arange(24).reshape(2,3,4)
a+X, (a+X).shape

(array([[[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]],
 
        [[14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.]]]),
 (2, 3, 4))

### 2.3.6 Reduction(数据降维)

In [10]:
x=np.arange(4)
x, x.shape, x.sum(), x.sum().shape

(array([0., 1., 2., 3.]), (4,), array(6.), ())

In [11]:
A=np.arange(20).reshape(5,4)
A.size, A.shape, A.sum()

(20, (5, 4), array(190.))

In [12]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis1=A.sum(axis=1)
A_sum=A.sum(axis=[0,1])
A_sum_axis0, A_sum_axis0.shape, A_sum_axis1, A_sum_axis1.shape, A_sum

(array([40., 45., 50., 55.]),
 (4,),
 array([ 6., 22., 38., 54., 70.]),
 (5,),
 array(190.))

In [13]:
A=np.arange(20).reshape(5,4)
A.mean(), A.sum()/A.size

(array(9.5), array(9.5))

In [14]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(array([ 8.,  9., 10., 11.]), array([ 8.,  9., 10., 11.]))

In [15]:
# 不降维求和
sum_A=A.sum(axis=1, keepdims=True)
sum_A, A/sum_A

(array([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]),
 array([[0.        , 0.16666667, 0.33333334, 0.5       ],
        [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
        [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
        [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
        [0.22857143, 0.24285714, 0.25714287, 0.27142859]]))

In [16]:
#  累积求和
A.cumsum(axis=0), A.cumsum(axis=1), A.cumsum()

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]]),
 array([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]]),
 array([  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.,  55.,
         66.,  78.,  91., 105., 120., 136., 153., 171., 190.]))

### 2.3.7 Dot Products(向量点积，向量乘向量)

In [17]:
x=np.arange(4)
y=np.ones(4)
x, y, x*y, np.dot(x,y), np.sum(x*y)

(array([0., 1., 2., 3.]),
 array([1., 1., 1., 1.]),
 array([0., 1., 2., 3.]),
 array(6.),
 array(6.))

### 2.3.8 Matrix-Vecotr Products(矩阵乘向量)

In [18]:
A=np.arange(20).reshape(5,4)
x=np.arange(4)
A.shape, x.shape, np.dot(A,x)

((5, 4), (4,), array([ 14.,  38.,  62.,  86., 110.]))

### 2.3.9 Matrix-Matrix Multiplication(矩阵乘矩阵)

In [19]:
A=np.arange(20).reshape(5,4)
B=np.ones(shape=(4,3))
np.dot(A,B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

### 2.3.10 Norms(范数)

向量范数：
-   $L_2$ 范数：$||\mathbf{x}||_2=\sqrt{\sum_{i=1}^n x_i^2}$
-   $L_1$ 范数：$||\mathbf{x}||_1=\sum_{i=1}^n |x_i|$
-   $L_p$ 范数：$||\mathbf{x}||_p=(\sum_{i=1}^n |x_i|^p)^{1/p}$

矩阵范数：
Frobenius 范数：$||\mathbf{X}||_F=\sqrt{\sum_{i=1}^m\sum_{j=1}^n x_{ij}^2}$

In [20]:
#L_2, L_1, X_F
u=np.array([3,-4])
X=np.ones((4,9))
np.linalg.norm(u), np.abs(u).sum(), np.linalg.norm(X)

(array(5.), array(7.), array(6.))